import { Example } from './api/compile'

export const examplesByLang: Record<string, Example[]> = {
  rust: [
    { name: 'Basic arithmetic', code: 'let x = 10;\nlet y = 20;\nprint x + y;' },
    { name: 'If/else branch', code: 'let a = 5;\nif a > 3 {\n  print a;\n} else {\n  print 0;\n}' },
    { name: 'While loop', code: 'let i = 0;\nwhile i < 5 {\n  print i;\n  i = i + 1;\n}' },
    { name: 'Operator precedence', code: 'let x = 1;\nlet y = 2;\nlet z = 3;\nprint x + y * z;\nprint (x + y) * z;\nprint x * y + z;' },
    { name: 'Factorial', code: 'let n = 5;\nlet fact = 1;\nwhile n > 0 {\n  fact = fact * n;\n  n = n - 1;\n}\nprint fact;' },
    { name: 'Sum 1 to 10', code: 'let sum = 0;\nlet i = 1;\nwhile i <= 10 {\n  sum = sum + i;\n  i = i + 1;\n}\nprint sum;' },
    { name: 'Max of three', code: 'let x = 10;\nlet y = 20;\nlet z = 30;\nif x > y {\n  if x > z {\n    print x;\n  } else {\n    print z;\n  }\n} else {\n  if y > z {\n    print y;\n  } else {\n    print z;\n  }\n}' },
    { name: 'Fibonacci', code: 'let a = 2;\nlet b = 1;\nwhile a < 100 {\n  print a;\n  let c = a + b;\n  b = a;\n  a = c;\n}' },
    { name: 'Even/odd', code: 'let x = 7;\nif x % 2 == 0 {\n  print 1;\n} else {\n  print 0;\n}' },
    { name: 'Triangle numbers', code: 'let n = 1;\nlet m = 1;\nwhile n <= 5 {\n  let j = 1;\n  while j <= n {\n    print m;\n    m = m + 1;\n    j = j + 1;\n  }\n  n = n + 1;\n}' },
    { name: 'Prime numbers', code: 'let i = 2;\nwhile i <= 20 {\n  let j = 2;\n  let prime = 1;\n  while j < i {\n    if i % j == 0 {\n      prime = 0;\n    }\n    j = j + 1;\n  }\n  if prime == 1 {\n    print i;\n  }\n  i = i + 1;\n}' },
    { name: 'Swap variables', code: 'let x = 1;\nlet y = 2;\nlet t = x;\nx = y;\ny = t;\nprint x;\nprint y;' },
    { name: 'Object literal', code: 'let p = [x = 10, y = 20];\nprint p.x;\nprint p.y;' },
    { name: 'Object expression', code: 'let p = [x = 5, y = 3];\nlet q = [x = p.x + p.y, y = p.x - p.y];\nprint q.x;\nprint q.y;' },
    { name: 'Class definition', code: 'class Point {\n  x = 0;\n  y = 0;\n}\nlet p = Point(10, 20);\nprint p.x;\nprint p.y;' },
    { name: 'Equality chain', code: 'let x = 1;\nlet y = 1;\nlet z = 1;\nif x == y {\n  if y == z {\n    print 1;\n  } else {\n    print 0;\n  }\n} else {\n  print 0;\n}' },
  ],
  go: [
    { name: 'Basic arithmetic', code: 'var x = 10;\nvar y = 20;\nprint x + y;' },
    { name: 'If/else branch', code: 'var a = 5;\nif a > 3 {\n  print a;\n} else {\n  print 0;\n}' },
    { name: 'While loop', code: 'var i = 0;\nwhile i < 5 {\n  print i;\n  i = i + 1;\n}' },
    { name: 'All operators', code: 'var x = 10;\nvar y = 3;\nprint x + y;\nprint x - y;\nprint x * y;\nprint x / y;\nprint x % y;' },
    { name: 'Factorial', code: 'var n = 5;\nvar fact = 1;\nwhile n > 0 {\n  fact = fact * n;\n  n = n - 1;\n}\nprint fact;' },
    { name: 'Fibonacci', code: 'var a = 1;\nvar b = 1;\nvar i = 0;\nwhile i < 8 {\n  var c = a + b;\n  print c;\n  a = b;\n  b = c;\n  i = i + 1;\n}' },
    { name: 'Even/odd', code: 'var x = 7;\nif x % 2 == 0 {\n  print 1;\n} else {\n  print 0;\n}' },
    { name: 'Pythagorean triple', code: 'var x = 4;\nvar y = 5;\nvar z = 6;\nprint x * x + y * y;\nprint z * z;\nprint x * x + y * y == z * z;' },
    { name: 'Swap variables', code: 'var x = 1;\nvar y = 2;\nvar z = x;\nx = y;\ny = z;\nprint x;\nprint y;' },
    { name: 'Triangle numbers', code: 'var n = 1;\nvar m = 1;\nwhile n <= 5 {\n  var j = 1;\n  while j <= n {\n    print m;\n    m = m + 1;\n    j = j + 1;\n  }\n  n = n + 1;\n}' },
    { name: 'Max of three', code: 'var x = 1;\nvar y = 2;\nvar z = 3;\nvar max = x;\nif y > max {\n  max = y;\n}\nif z > max {\n  max = z;\n}\nprint max;' },
    { name: 'Grid (nested while)', code: 'var x = 0;\nvar y = 0;\nwhile x < 3 {\n  y = 0;\n  while y < 3 {\n    print x * 3 + y;\n    y = y + 1;\n  }\n  x = x + 1;\n}' },
    { name: 'Object literal', code: 'var p = [x = 10, y = 20];\nprint p.x;\nprint p.y;' },
    { name: 'Object + math', code: 'var p = [x = 3, y = 4];\nprint p.x * p.x + p.y * p.y;' },
  ],
  python: [
    { name: 'Basic arithmetic', code: 'x = 10\ny = 20\nprint(x + y)' },
    { name: 'If/else branch', code: 'a = 5\nif a > 3 {\n  print(a)\n} else {\n  print(0)\n}' },
    { name: 'While loop', code: 'i = 0\nwhile i < 5 {\n  print(i)\n  i = i + 1\n}' },
    { name: 'Operator precedence', code: 'x = 1\ny = 2\nz = 3\nprint(x + y * z)\nprint((x + y) * z)' },
    { name: 'Factorial', code: 'n = 5\nfact = 1\nwhile n > 0 {\n  fact = fact * n\n  n = n - 1\n}\nprint(fact)' },
    { name: 'Fibonacci', code: 'a = 0\nb = 1\ni = 0\nwhile i < 8 {\n  c = a + b\n  print(c)\n  a = b\n  b = c\n  i = i + 1\n}' },
    { name: 'Max of three', code: 'x = 10\ny = 20\nz = 30\nif x > y {\n  if x > z {\n    print(x)\n  } else {\n    print(z)\n  }\n} else {\n  if y > z {\n    print(y)\n  } else {\n    print(z)\n  }\n}' },
    { name: 'Swap variables', code: 'x = 1\ny = 2\nz = x\nx = y\ny = z\nprint(x)\nprint(y)' },
    { name: 'Even/odd', code: 'x = 7\nif x % 2 == 0 {\n  print(1)\n} else {\n  print(0)\n}' },
    { name: 'Triangle numbers', code: 'n = 1\nm = 1\nwhile n <= 5 {\n  j = 1\n  while j <= n {\n    print(m)\n    m = m + 1\n    j = j + 1\n  }\n  n = n + 1\n}' },
    { name: 'Grid (nested while)', code: 'x = 0\nwhile x < 3 {\n  y = 0\n  while y < 3 {\n    print(x * 3 + y)\n    y = y + 1\n  }\n  x = x + 1\n}' },
    { name: 'Absolute value', code: 'x = 7\nif x >= 0 {\n  print(x)\n} else {\n  print(0 - x)\n}' },
    { name: 'Object literal', code: 'p = [x = 10, y = 20]\nprint(p.x)\nprint(p.y)' },
    { name: 'Object + math', code: 'p = [x = 3, y = 4]\nprint(p.x * p.x + p.y * p.y)' },
  ],
  typescript: [
    { name: 'Basic arithmetic', code: 'let x = 10;\nlet y = 20;\nprint x + y;' },
    { name: 'If/else branch', code: 'let a = 5;\nif a > 3 {\n  print a;\n} else {\n  print 0;\n}' },
    { name: 'While loop', code: 'let i = 0;\nwhile i < 5 {\n  print i;\n  i = i + 1;\n}' },
    { name: 'Operator precedence', code: 'let x = 1;\nlet y = 2;\nlet z = 3;\nprint x + y * z;\nprint (x + y) * z;\nprint x * y + z;' },
    { name: 'Factorial', code: 'let n = 5;\nlet fact = 1;\nwhile n > 0 {\n  fact = fact * n;\n  n = n - 1;\n}\nprint fact;' },
    { name: 'Sum 1 to 100', code: 'let sum = 0;\nlet i = 1;\nwhile i <= 100 {\n  sum = sum + i;\n  i = i + 1;\n}\nprint sum;' },
    { name: 'Absolute value', code: 'let x = 7;\nif x >= 0 {\n  print x;\n} else {\n  print 0 - x;\n}' },
    { name: 'Volume calculation', code: 'let a = 3;\nlet b = 4;\nlet c = 5;\nprint a + b + c;\nprint a * b * c;\nprint a * a + b * b;\nprint c * c;' },
    { name: 'Fibonacci', code: 'let a = 2;\nlet b = 1;\nwhile a < 100 {\n  print a;\n  let c = a + b;\n  b = a;\n  a = c;\n}' },
    { name: 'Max of three', code: 'let x = 1;\nlet y = 2;\nlet z = 3;\nlet max = x;\nif y > max { max = y; }\nif z > max { max = z; }\nprint max;' },
    { name: 'Grid (nested while)', code: 'let x = 0;\nwhile x < 3 {\n  let y = 0;\n  while y < 3 {\n    print x * 3 + y;\n    y = y + 1;\n  }\n  x = x + 1;\n}' },
    { name: 'Even/odd', code: 'let x = 7;\nif x % 2 == 0 {\n  print 1;\n} else {\n  print 0;\n}' },
    { name: 'Swap variables', code: 'let x = 1;\nlet y = 2;\nlet t = x;\nx = y;\ny = t;\nprint x;\nprint y;' },
    { name: 'Object literal', code: 'let p = [x = 10, y = 20];\nprint p.x;\nprint p.y;' },
    { name: 'Object expression', code: 'let p = [x = 5, y = 3];\nlet q = [x = p.x + p.y, y = p.x - p.y];\nprint q.x;\nprint q.y;' },
  ],
  c: [
    { name: 'Basic arithmetic', code: 'int x = 10;\nint y = 20;\nprintf x + y;' },
    { name: 'If/else branch', code: 'int a = 5;\nif a > 3 {\n  printf a;\n} else {\n  printf 0;\n}' },
    { name: 'While loop', code: 'int i = 0;\nwhile i < 5 {\n  printf i;\n  i = i + 1;\n}' },
    { name: 'All operators', code: 'int x = 10;\nint y = 3;\nprintf x + y;\nprintf x * y;\nprintf x / y;\nprintf x % y;' },
    { name: 'Factorial', code: 'int n = 5;\nint fact = 1;\nwhile n > 0 {\n  fact = fact * n;\n  n = n - 1;\n}\nprintf fact;' },
    { name: 'Fibonacci', code: 'int a = 0;\nint b = 1;\nint i = 0;\nwhile i < 10 {\n  int c = a + b;\n  printf c;\n  a = b;\n  b = c;\n  i = i + 1;\n}' },
    { name: 'Even/odd', code: 'int x = 7;\nif x % 2 == 0 {\n  printf 1;\n} else {\n  printf 0;\n}' },
    { name: 'Sum 1 to 100', code: 'int sum = 0;\nint i = 1;\nwhile i <= 100 {\n  sum = sum + i;\n  i = i + 1;\n}\nprintf sum;' },
    { name: 'Swap variables', code: 'int x = 1;\nint y = 2;\nint t = x;\nx = y;\ny = t;\nprintf x;\nprintf y;' },
    { name: 'Triangle numbers', code: 'int n = 1;\nint m = 1;\nwhile n <= 5 {\n  int j = 1;\n  while j <= n {\n    printf m;\n    m = m + 1;\n    j = j + 1;\n  }\n  n = n + 1;\n}' },
    { name: 'Pythagorean check', code: 'int x = 4;\nint y = 5;\nint z = 6;\nint a = x * x + y * y;\nprintf a;\nprintf z * z;\nif a == z * z {\n  printf 1;\n} else {\n  printf 0;\n}' },
    { name: 'Object literal', code: 'int p = [x = 10, y = 20];\nprintf p.x;\nprintf p.y;' },
    { name: 'Object + math', code: 'int p = [x = 3, y = 4];\nprintf p.x * p.x + p.y * p.y;' },
  ],
}
